### ISSUE TITLE
Merge a ZH előtt

### ISSUE THREAD

**Issue by bokrosbalint** [FTSRG/remo#12]
A 02-struktura-alapu-modellezes és 06-teljesitmenymodellezes branchek késznek, vagy legalábbis a jelenleg [itt](http://docs.inf.mit.bme.hu/remo) elérhetőnél frissebbnek tűnnek. Megoldható, hogy ezek a ZH előtt bekerüljenek a gh-pages branchbe?

**Comment by bokrosbalint** [comment]
Közben rájöttem, hogy ezt pull requestekkel több értelme van megcsinálni: #13 #14

**Comment by szarnyasg** [comment]
Szia!

A teljesítménymodellezés nem anyaga a zh-nak. A struktúra alapú modellezés igen, de még work-in-progress a dolog.

Üdv.
Gábor

**Comment by bokrosbalint** [comment]
Rendben, köszönöm.

Üdv,
Bokros Bálint
